
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cromwell
  labels: { app: cromwell }
spec:
  replicas: 1
  selector:
    matchLabels: { app: cromwell }
  template:
    metadata:
      labels: { app: cromwell }
    spec:
      containers:
      - name: cromwell
        image: broadinstitute/cromwell:85
        ports: [{ containerPort: 8000 }]
        env:
        - name: BATCH_ACCOUNT
          valueFrom: { secretKeyRef: { name: cromwell-azure, key: BATCH_ACCOUNT } }
        - name: BATCH_URL
          valueFrom: { secretKeyRef: { name: cromwell-azure, key: BATCH_URL } }
        - name: BATCH_KEY
          valueFrom: { secretKeyRef: { name: cromwell-azure, key: BATCH_KEY } }
        - name: STORAGE_ACCOUNT
          valueFrom: { secretKeyRef: { name: cromwell-azure, key: STORAGE_ACCOUNT } }
        - name: STORAGE_CONTAINER
          valueFrom: { secretKeyRef: { name: cromwell-azure, key: STORAGE_CONTAINER } }
        - name: STORAGE_SAS
          valueFrom: { secretKeyRef: { name: cromwell-azure, key: STORAGE_SAS } }
        volumeMounts:
        - { name: cromwell-conf, mountPath: /cromwell/conf }
        - { name: cromwell-exec, mountPath: /cromwell-exec }
        args: ["server", "-Dconfig.file=/cromwell/conf/cromwell.conf"]
      volumes:
      - name: cromwell-conf
        configMap: { name: cromwell-config }
      - name: cromwell-exec
        emptyDir: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: cromwell-azure
type: Opaque
stringData:
  BATCH_ACCOUNT: "<batch-account-name>"
  BATCH_URL: "https://<region>.batch.azure.com"
  BATCH_KEY: "<batch-account-key-or-empty-if-using-COA/TES>"
  STORAGE_ACCOUNT: "<storage-account-name>"
  STORAGE_CONTAINER: "cromwell"
  STORAGE_SAS: "<sas-token-from_issue-sas.sh>"
