apiVersion: apps/v1
kind: Deployment
metadata:
  name: cromwell
  namespace: genomics
  labels: { app: cromwell }
spec:
  replicas: 1
  selector:
    matchLabels: { app: cromwell }
  template:
    metadata:
      labels: { app: cromwell }
    spec:
      serviceAccountName: cromwell-sa
      volumes:
      - name: kv-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: kv-cromwell-sas
      containers:
      - name: cromwell
        image: broadinstitute/cromwell:85
        ports: [{ containerPort: 8000 }]
        env:
        - name: BATCH_ACCOUNT
          value: "<batch-account-name>"
        - name: BATCH_URL
          value: "https://<region>.batch.azure.com"
        # BATCH_KEY optional when using TES/MI; leave empty or prefer TES
        - name: BATCH_KEY
          value: ""
        - name: STORAGE_ACCOUNT
          value: "<storage-account-name>"
        - name: STORAGE_CONTAINER
          value: "cromwell"
        - name: STORAGE_SAS
          valueFrom:
            secretKeyRef:
              name: cromwell-sas
              key: sas
        volumeMounts:
        - { name: kv-secrets, mountPath: "/mnt/kv", readOnly: true }
        args: ["server", "-Dconfig.file=/cromwell/conf/cromwell.conf"]
      # cromwell.conf ConfigMap must be applied separately (see existing file)