apiVersion: v1
kind: ServiceAccount
metadata: { name: genomics-sa }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: { name: genomics-role }
rules:
- apiGroups: [""]
  resources: ["pods","pods/log","configmaps","secrets"]
  verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: { name: genomics-rb }
subjects: [ { kind: ServiceAccount, name: genomics-sa } ]
roleRef: { kind: Role, name: genomics-role, apiGroup: rbac.authorization.k8s.io }
