apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-cromwell-sas
  namespace: genomics
spec:
  provider: azure
  parameters:
    keyvaultName: "<your-key-vault-name>"
    cloudName: "AzurePublicCloud"
    tenantId: "<your-tenant-id>"
    # If using Azure Workload Identity, set clientID to UAMI client id and set usePodIdentity to "false"
    clientID: "<uami-client-id>"
    usePodIdentity: "false"
    objects: |
      array:
        - |
          objectName: cromwell-storage-sas
          objectType: secret
          objectVersion: ""
  secretObjects:
  - secretName: cromwell-sas
    type: Opaque
    data:
    - objectName: cromwell-storage-sas
      key: sas