apiVersion: v1
kind: Namespace
metadata:
  name: tes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tes-sa
  namespace: tes
  annotations:
    azure.workload.identity/use: "true"
    azure.workload.identity/client-id: "<uami-client-id>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tes
  namespace: tes
  labels: { app: tes }
spec:
  replicas: 1
  selector: { matchLabels: { app: tes } }
  template:
    metadata: { labels: { app: tes } }
    spec:
      serviceAccountName: tes-sa
      containers:
      - name: tes
        # Replace with an official TES image for Azure Batch (e.g., ghcr.io/microsoft/tes:<tag>)
        image: ghcr.io/microsoft/tes:latest
        ports: [{ containerPort: 80 }]
        env:
        - name: AZURE_BATCH_ACCOUNT_NAME
          value: "<batch-account-name>"
        - name: AZURE_BATCH_ENDPOINT
          value: "https://<region>.batch.azure.com"
        - name: AZURE_STORAGE_ACCOUNT_NAME
          value: "<storage-account-name>"
        - name: AZURE_STORAGE_CONTAINER_NAME
          value: "tes"
        # TES will use Workload Identity to get tokens; no keys needed
---
apiVersion: v1
kind: Service
metadata:
  name: tes
  namespace: tes
spec:
  selector: { app: tes }
  ports:
  - name: http
    port: 80
    targetPort: 80