apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orthanc-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orthanc-config
data:
  orthanc.json: |
    {
      "Name": "Orthanc",
      "StorageDirectory": "/var/lib/orthanc/db",
      "IndexDirectory": "/var/lib/orthanc/db-index",
      "DicomAet": "ORTHANC",
      "DicomPort": 4242,
      "HttpPort": 8042,
      "HttpServerEnabled": true,
      "AuthenticationEnabled": true,
      "RegisteredUsers": { "orthanc": "orthanc" },
      "MaximumStorageSize": 0,
      "MaximumPatientCount": 0,
      "DicomWeb": { "Enable": true, "Root": "/dicom-web/" }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc
spec:
  replicas: 1
  selector:
    matchLabels: { app: orthanc }
  template:
    metadata:
      labels: { app: orthanc }
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: orthanc
        image: orthanc/orthanc:latest
        ports:
          - containerPort: 8042
          - containerPort: 4242
        volumeMounts:
          - name: data
            mountPath: /var/lib/orthanc
          - name: config
            mountPath: /etc/orthanc
        readinessProbe:
          httpGet: { path: /, port: 8042 }
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: orthanc-pvc }
        - name: config
          configMap:
            name: orthanc-config
---
apiVersion: v1
kind: Service
metadata:
  name: orthanc-svc
spec:
  selector: { app: orthanc }
  ports:
    - name: http
      port: 80
      targetPort: 8042
    - name: dicom
      port: 4242
      targetPort: 4242
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: orthanc
spec:
  to: { kind: Service, name: orthanc-svc }
  port: { targetPort: http }
  tls: { termination: edge }
